const data = {
	products: [
		{
			_id: "1",
			name: "Nike Slim Shirt",
			category: "Shirts",
			image: "/images/p1.jpg",
			price: 1299,
			countInStock: 10,
			brand: "Nike",
			rating: 4.5,
			numReviews: 10,
			description: "high quality product",
		},
		{
			_id: "2",
			name: "Adidas Fit Shirt",
			category: "Shirts",
			image: "/images/p2.jpg",
			price: 1999,
			countInStock: 20,
			brand: "Adidas",
			rating: 4.0,
			numReviews: 10,
			description: "high quality product",
		},
		{
			_id: "3",
			name: "Lacoste Free Shirt",
			category: "Shirts",
			image: "/images/p3.jpg",
			price: 2209,
			countInStock: 0,
			brand: "Lacoste",
			rating: 4.8,
			numReviews: 17,
			description: "high quality product",
		},
		{
			_id: "4",
			name: "Nike Slim Pant",
			category: "Pants",
			image: "/images/p4.jpg",
			price: 2999,
			countInStock: 15,
			brand: "Nike",
			rating: 4.5,
			numReviews: 14,
			description: "high quality product",
		},
		{
			_id: "5",
			name: "Puma Slim Pant",
			category: "Pants",
			image: "/images/p5.jpg",
			price: 3999,
			countInStock: 5,
			brand: "Puma",
			rating: 4.5,
			numReviews: 10,
			description: "high quality product",
		},
		{
			_id: "6",
			name: "Adidas Fit Pant",
			category: "Pants",
			image: "/images/tshirt-t1.jpeg",
			price: 3339,
			countInStock: 0,
			brand: "Adidas",
			rating: 4.5,
			numReviews: 15,
			description:
				"High quality product High quality product High quality product High quality product High quality product High quality product",
		},
	],
};
export default data;
